# Tensorflow 2.0 Introduction

### What is tensorflow?
Tensorflow is open source machine learning platform API by Google.

Tensorflow can be used to build models for:
- Image Classification
- Data Clustering
- Regression
- Reinforcement Learning
- Natural Language Processing

Tensorflow has two main components
- Graphs
- Sessions

Tensorflow works by building a graph of defined computations. Nothing is computed or stored in graph. It is just a way of defining the operation that have been written in code.

Tensorflow session allows parts of graph to be executed. It allocates memory and resources and handles the execution of operations and computations we have defined.

In [1]:
# Importing tensorflow module in python
import tensorflow as tf

### Checking version of tensorflow

#### In Tensorflow 2.0, eager execution is enabled by default.

In [2]:
print("Tensorflow version installed is:", tf.__version__)

Tensorflow version installed is: 2.2.0


## Tensors 
"A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes." (https://www.tensorflow.org/guide/tensor)

It should't surprise you that tensors are a fundemental apsect of TensorFlow. They are the main objects that are passed around and manipluated throughout the program. Each tensor represents a partialy defined computation that will eventually produce a value. TensorFlow programs work by building a graph of Tensor objects that details how tensors are related. Running different parts of the graph allow results to be generated.

Each tensor has a data type and a shape. 

**Data Types Include**: float32, int32, string and others.

**Shape**: Represents the dimension of data.

Just like vectors and matrices tensors can have operations applied to them like addition, subtraction, dot product, cross product etc.

In the next sections we will discuss some different properties of tensors. This is to make you more familiar with how tensorflow represnts data and how you can manipulate this data.

#### Creating Tensors

In [3]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

## Data types in tensorflow (later)

### Rank/Degree of Tensors
Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor. What we created above is a *tensor of rank 0*, also known as a scalar. 

Now we'll create some tensors of higher degrees/ranks

In [4]:
rank1_tensor = tf.Variable(["list"], tf.string)
rank2_tensor = tf.Variable([["list", "inside"],["list","ok"]], tf.string)

In [5]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

### Shape of Tensors
Now that we've talked about the rank of tensors it's time to talk about the shape. The shape of a tensor is simply the number of elements that exist in each dimension. TensorFlow will try to determine the shape of a tensor but sometimes it may be unknown.

To **get the shape** of a tensor we use the shape attribute.


In [6]:
rank2_tensor.shape

TensorShape([2, 2])

### Changing Shape
The number of elements of a tensor is the product of the sizes of all its shapes. There are often many shapes that have the same number of elements, making it convient to be able to change the shape of a tensor.

The example below shows how to change the shape of a tensor.

In [7]:
tensor1 = tf.ones([1,2,3]) # tf.ones() creates tensor full of ones with shape given ([1,2,3])
tensor2 = tf.reshape(tensor1, [2,3,1]) # reshape into shape[2,3,1]
tensor3 = tf.reshape(tensor2, [3,-1]) # -1 tells tensor to calculate the size of dimension remaining
                                        # this gives us [3,3]
# The numer of elements in the reshaped tensor MUST match the number in the original

In [8]:
print(tensor1)
print(tensor2)
print(tensor3)
# Notice the changes in shape

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


### Slicing Tensors
You may be familiar with the term "slice" in python and its use on lists, tuples etc. Well the slice operator can be used on tensors to select specific axes or elements.

When we slice or select elements from a tensor, we can use comma seperated values inside the set of square brackets. Each subsequent value refrences a different dimension of the tensor.

Ex: ```tensor[dim1, dim2, dim3]```

I've included a few examples that will hopefully help illustrate how we can manipulate tensors with the slice operator.

In [9]:
# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

TENSOR = tf.Variable(matrix, dtype=tf.int32) 
print(tf.rank(TENSOR))
print(TENSOR.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [10]:
# Now lets select some different rows and columns from our tensor

three = TENSOR[0,2]  # selects the 3rd element from the 1st row
print(three)  # -> 3

row1 = TENSOR[0]  # selects the first row
print(row1)

column1 = TENSOR[:, 0]  # selects the first column
print(column1)

row_2_and_4 = TENSOR[1::2]  # selects second and fourth row
print(row_2_and_4)

column_1_in_row_2_and_3 = TENSOR[1:3, 0]
print(column_1_in_row_2_and_3)


tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)
tf.Tensor([ 6 11], shape=(2,), dtype=int32)


### Types of Tensors
Before we go to far, I will mention that there are diffent types of tensors. These are the most used and we will talk more in depth about each as they are used.
- Variable
- Constant
- Placeholder
- SparseTensor

With the execption of ```Variable``` all these tensors are immuttable, meaning their value may not change during execution.

For now, it is enough to understand that we use the Variable tensor when we want to potentially change the value of our tensor.



In [12]:
# Broadcasting
print(tf.broadcast_to(tf.constant([1,2,3]), [3,3]))

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


Most ops, like `tf.matmul` and `tf.reshape` take arguments of class `tf.Tensor`.
But not all operations are tensor. To convert something in to tensor use 
`tf.convert_to_tensor`

### Evaluating Tensors
There will be some time that we need to evaluate a tensor. In other words, get its value. Since tensors represent a partially complete computation we will need to run session to evaluate the tensor.

In [11]:


with tf.Session() as sess: # creates session using default graph
    TENSOR.eval()          # TENSOR is the name of the tensor

AttributeError: module 'tensorflow' has no attribute 'Session'

# Sources
Most of the information is taken direclty from the TensorFlow website which can be found below.

https://www.tensorflow.org/guide/tensor